/**
 * Highly divisible triangular number
 *
 * The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
 *
 * http://projecteuler.net/problem=12
 */

(function() {
	'use strict';

	var startTime = new Date().getTime(),

		findDevisors = function(value) {
			// var devisors = [];
			var count = 0;

			for (var i = 0; i <= Math.sqrt(value); i++) {
				if (value % i === 0) {
					count += 2;
					// devisors.push(i);
					// devisors.push(value / i);
				}
			}

			// return devisors;
			return count;
		},
		
		findSolution = function() {
			// TODO: Make method that iterates over triangle numbers
			// TODO: Use object literal notation

			var currentTriangle = 0,
				triangles = [1],
				count = 0;

			// Start at 1000 to save some time
			for (var i = 1; i <= 15000; i++) {
				currentTriangle = currentTriangle + i;

				// var n = triangles[triangles.length - 1] + i;
				// triangles.push(n);

				var divisors = findDevisors(currentTriangle);

				if (divisors > 500) {
					console.log(currentTriangle);
					return;
				}
			}
		};

	findSolution();

	console.log('Time elapsed: ' + (new Date().getTime() - startTime) / 1000 + ' seconds');
	
}());