/**
 * Highly divisible triangular number
 *
 * The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
 *
 * http://projecteuler.net/problem=12
 */

var problem12 = (function() {
	'use strict';

	var MIN_DIVISORS = 500,
		startTime,

		findDivisors = function(value) {
			// var divisors = [];		// Put the found divisors in an array
			var count = 0;

			for (var i = 0; i <= Math.sqrt(value); i++) {
				if (value % i === 0) {
					count += 2;
					// divisors.push(i);
					// divisors.push(value / i);
				}
			}

			return count;
		},
		
		findSolution = function() {
			var currentTriangle = 0,
				divisorCount = 0,
				index = 1;

			// Iterate till the divisorCount is bigger than 500
			while (divisorCount < MIN_DIVISORS) {
				// Triangle number
				currentTriangle = currentTriangle + index;

				// Number of divisors for the triangle number
				divisorCount = findDivisors(currentTriangle);

				index++;
			}

			console.log('Triangle number: ' + currentTriangle);		// Result
			console.log('Number of divisors: ' + divisorCount);

			// Show the elapsed time
			console.log('Time elapsed: ' + (new Date().getTime() - startTime) / 1000 + ' seconds');
		};

	return {
		init: function() {
			startTime = new Date().getTime();
			
			findSolution();
		},

		findDivisors: findDivisors
	};
}());

problem12.init();